name: Build OpenWrt

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ImageBuilder
        run: |
          wget https://downloads.openwrt.org/snapshots/targets/ath79/generic/openwrt-imagebuilder-ath79-generic.Linux-x86_64.tar.xz
          tar -xf openwrt-imagebuilder-ath79-generic.Linux-x86_64.tar.xz

      - name: Copy config
        run: cp .config ./openwrt-imagebuilder-ath79-generic.Linux-x86_64/.config

      - name: Build firmware
        working-directory: ./openwrt-imagebuilder-ath79-generic.Linux-x86_64
        run: make image PROFILE=letv_lba-047-ch PACKAGES="luci luci-i18n-base-zh-cn luci-i18n-firewall-zh-cn luci-i18n-opkg-zh-cn luci-app-passwall ipset dnsmasq-full wget curl luci-proto-qmi kmod-usb-net-qmi-wwan uqmi usb-modeswitch kmod-usb-serial-option kmod-usb-serial ppp ppp-mod-pppoe kmod-usb2 kmod-usb-ohci block-mount kmod-fs-ext4 luci-compat luci-lib-ipkg"

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-firmware
          path: ./openwrt-imagebuilder-ath79-generic.Linux-x86_64/bin/targets/ath79/generic/*.bin
